theme: jekyll-theme-minimal
title: Juan Camilo Avendaño Díaz
description: Description



twitter:
  username               : juancamiload


# Site Author
author:
  name             : "..."
  avatar           : 
  bio              : 
  location         : "UK"
  email            : "enrico.glerean@utu.fi"
  github           : "eglerean"
  linkedin         : "http://fi.linkedin.com/in/enricoglerean"
  twitter          : "eglerean"

