theme: jekyll-theme-minimal
title: Juan Camilo Avendaño Díaz
description: Description



twitter:
  username               : juancamiload


# Site Author
author:
  name             : "..."
  avatar           : 
  bio              : 
  location         : "UK"
  email            : "javendanodiaz@bournemouth.ac.uk"
  github           : "juancamiload"
  linkedin         : 
  twitter          : "juancamiload"

